# Generated by Django 6.0.5 on 2026-05-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=50)),
                ('laptop', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('check_box', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('ram', models.IntegerField()),
                ('youtube_channel', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
